import React from 'react'
import { StartonFaq } from './common/StartonFaq'

/*
|--------------------------------------------------------------------------
| Contract
|--------------------------------------------------------------------------
*/
export interface FAQProps {}

/*
|--------------------------------------------------------------------------
| Component
|--------------------------------------------------------------------------
*/
export const FAQ: React.FC<FAQProps> = () => {
	// Render
	//--------------------------------------------------------------------------
	return (
		<StartonFaq
			uniqueExpand={true}
			title="Frequently asked questions"
			items={[
				{
					summary: 'What is this page?',
					details:
						'This page allow you to deploy a NFT collection with visuals generated by an AI in the simplest way. You just have two buttons, one to generate your pictures, another to deploy your collection.',
					seo: {
						questionName: 'What is this page?',
						acceptedAnswerText:
							'This page allow you to deploy a NFT collection with visuals generated by an AI in the simplest way. You just have two buttons, one to generate your pictures, another to deploy your collection',
					},
				},
				{
					summary: 'Which AI is used to generate the pictures?',
					details:
						'For this PoC, we used the DALL-E 2 model developed by Open AI (https://openai.com/product/dall-e-2).',
					seo: {
						questionName: 'Which AI is used to generate the pictures?',
						acceptedAnswerText:
							'For this PoC, we used the DALL-E 2 model developed by Open AI (https://openai.com/product/dall-e-2).',
					},
				},
				{
					summary: 'Do I need to connect with my wallet?',
					details:
						'No, you don\'t need to connect your Metamask wallet, all is handled by the backend KMS wallet.',
					seo: {
						questionName: 'Do I need to connect with my wallet?',
						acceptedAnswerText:
							'No, you don\'t need to connect your Metamask wallet, all is handled by the backend KMS wallet.',
					},
				},
				{
					summary: 'Where are stored the pictures and the metadata of my NFTs?',
					details:
						'All the data and the metadata are stored in a distributed way using IPFS. This is the most secure way to be sure that your NFT is always available and cannot be corrupted, modified or unavailable.',
					seo: {
						questionName: 'Where are stored the pictures and the metadata of my NFTs?',
						acceptedAnswerText:
							'All the data and the metadata are stored in a distributed way using IPFS. This is the most secure way to be sure that your NFT is always available and cannot be corrupted, modified or unavailable.',
					},
				},
				{
					summary: 'Can I custom this PoC?',
					details:
						'Obviously ! You can access the public GitHub repository at https://github.com/starton-io/XXX_TO_DO_XXX and you have a tutorial to reproduce it at https://docs.starton.io/XXX_TO_DO_XXX. You need only 3 things : a Starton API key (available at https://app.starton.io), a wallet on the Starton KMS, and an Open AI API key (available at https://platform.openai.com/account/api-keys)',
					seo: {
						questionName: 'Can I custom this PoC?',
						acceptedAnswerText:
							'Obviously ! You can access the public GitHub repository at https://github.com/starton-io/XXX_TO_DO_XXX and you have a tutorial to reproduce it at https://docs.starton.io/XXX_TO_DO_XXX. You need only 3 things : a Starton API key (available at https://app.starton.io), a wallet on the Starton KMS, and an Open AI API key (available at https://platform.openai.com/account/api-keys)',
					},
				},
				{
					summary: 'What is Starton?',
					details:
						'Starton provides developers with a full set of tools to integrate WEB3 features into web applications without thinking about blockchain complexity. Please visit our website for further information (https://www.starton.io)',
					seo: {
						questionName: 'What is Starton?',
						acceptedAnswerText:
							'Starton provides developers with a full set of tools to integrate WEB3 features into web applications without thinking about blockchain complexity. Please visit our website for further information (https://www.starton.io)',
					},
				},
			]}
		/>
	)
}
